Eventos.Mvc/Controllers/ComentariosController.cs
using Eventos.Models;
using Eventos.UnitOfWork;
using log4net;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Eventos.Mvc.Controllers
{
    public class ComentariosController : BaseController
    {
        public ComentariosController(ILog log, IUnitOfWork unit) : base(log, unit) { }

        public ActionResult Create(int Id, string Url)
        {
            ViewBag.IdEvento = Id;
            ViewBag.Url = Url;
            return View();
        }

        [HttpPost]
        public ActionResult Create(Comentario comentario, int Id, string Url)
        {
           if (ModelState.IsValid) { 
                comentario.IdEvento = Id;
                comentario.IdUsuario = User.Identity.GetUserId();
                comentario.Fecha = DateTime.Today;
                int result = _unit.Comentarios.Insert(comentario);
                return Redirect(Url);
            }
            ViewBag.IdEvento = Id;
            ViewBag.Url = Url;
            return View(comentario);

      
        }

    
        public ActionResult Delete(int Id, string Url)
        {
            var comentario = _unit.Comentarios.GetById(Id);
            _unit.Comentarios.Delete(comentario);
            return Redirect(Url);
        }
    }
}

Eventos.Mvc/Views/Comentarios/Create.cshtml
@model Eventos.Models.Comentario

@{
    ViewBag.Title = "Create";

}

<h2>Create</h2>

@using (Html.BeginForm("Create","Comentarios", new { Id=ViewBag.IdEvento,Url= ViewBag.Url }))
{


    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Comentario</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.Contenido, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Contenido, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Contenido, "", new { @class = "text-danger" })
        </div>
    </div>

 
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Eventos.Mvc/Views/Comentarios/_List.cshtml
@model Eventos.Mvc.ViewModels.EventoViewModel

<table class="table itemVer itembak" data-id="@Model.evento.Id">
    <tr>
        <th>
            Contenido
        </th>
        <th>
            Usuario
        </th>
        <th>
            Fecha
        </th>
    </tr>
    @foreach (var cmt in Model.comentarios)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => cmt.comentario.Contenido)
            </td>
            <td>
                @Html.DisplayFor(modelItem => cmt.autor.Email)
            </td>
            <td>
                @cmt.comentario.Fecha.ToString("dd/MM/yyyy")

            </td>
            <td>
                @if (ViewBag.band || (ViewBag.UserRol == Utils.RolAdministrador || (ViewBag.UserRol == Utils.RolUsuario && (ViewBag.UserId == cmt.autor.Id))))
                {
                    @Html.ActionLink("Eliminar", "Delete", "Comentarios", new { Id = cmt.comentario.Id, Url = ViewBag.Url}, new { onclick = "return confirm('Está seguro de eliminar este comentario?');" })
                }
            </td>
        </tr>


    }
</table>